### ISSUE TITLE
Sprint 1 review issues

### ISSUE THREAD

**Issue by Khater47** [SE-2223-Team19/Hike-Tracker#8]
### Colorful GUI design:
* The design looks very good and simple, but it can use more colors to get the user's attention on key actions and features.
### Hikes list
* Using cards in the hike list is nice and the icons used are a good touch. regarding the filters, it will be useful to have more filter options regarding the geographical filter, like a province, etc.

**Comment by matteorosani** [comment]
Thanks for your tips.
We added colors in the UI for the home page, but we kept our theme because we liked it.
For the filtering is now present a live map where you can select the area in which you want to search for hikes.

We thought about adding province and other geographical references but for this sprint we focused on more important things. We could address it in the future.

**Comment by victor3099** [comment]
We have add more geographical filters for the map
